version: '3'
services:
  nginx:
    image: nginx:1.19.2-alpine
    container_name: training-web
    ports:
      - 58089:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: training-php
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0.21
    container_name: training-db
    ports:
      - 53306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/conf/my.cnf:/etc/my.cnf
      - ./logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study
      MYSQL_USER: fujiko
      MYSQL_PASSWORD: fujiko

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: training-phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_USER=root
        - PMA_PASSWORD=changeme
      links:
        - db
      ports:
        - 58088:80
      depends_on:
        - db

volumes:
  db-store:
